services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_AUTH_URL=https://auth.api.xpectrum-ai.com
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - AUTH_URL=https://auth.api.xpectrum-ai.com
      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge