version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - AUTH_URL= https://auth.api.xpectrum-ai.com
      - PROPELAUTH_API_KEY=39ba5d0fa20b8f7a25b22a5370188e2ed30d0d57db24deb66b1be755c1ef69c85979d717100d0f5b5d5cd22958518819
    networks:
      - app-network

networks:
  app-network:
    driver: bridge